server:
  port: ${PORT:9090}
dmz:
  microservices: config-service,edge-gateway,edge-service,guardian,discovery-eureka
spring:
  main:
    allow-bean-definition-overriding: true
  cloud:
    loadbalancer:
      retry:
        enabled: false
    gateway:
#      default-filters:
#        - TokenRelay
#        - RemoveRequestHeader=Cookie
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
ribbon:
  ReadTimeout: 15000


---
spring:
  config:
    activate:
      on-profile: default | dev
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9092/eureka/
---
spring:
  config:
    activate:
      on-profile: test
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9092/eureka/

---
spring:
  config:
    activate:
      on-profile: prod
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9092/eureka/

